import type { Metadata } from "next";
import "../globals.css";
import { WebSocketProvider } from "../context/Websocketcontext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ChatLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
        <WebSocketProvider>

        {children}
        </WebSocketProvider>
   
  );
}